: CELL 8 ;
: TRUE -1 ;
: FALSE 0 ;

: DUP CALL ;
: DROP CALL ;
: SWAP CALL ;
: OVER CALL ;
: NIP CALL ;
: TUCK CALL ;
: ROT CALL ;
: ?DUP CALL ;
: DEPTH CALL ;

: + CALL ;
: - CALL ;
: * CALL ;
: / CALL ;
: MOD CALL ;
: /MOD CALL ;
: 1+ 1 + ;
: 1- 1 - ;
: 2* 2 * ;
: 2/ 2 / ;
: NEGATE 0 SWAP - ;
: ABS DUP 0< IF NEGATE THEN ;
: MIN 2DUP > IF SWAP THEN DROP ;
: MAX 2DUP < IF SWAP THEN DROP ;
: AND CALL ;
: OR CALL ;
: XOR CALL ;
: INVERT CALL ;
: LSHIFT CALL ;
: RSHIFT CALL ;

: = CALL ;
: <> CALL ;
: < CALL ;
: > CALL ;
: <= CALL ;
: >= CALL ;
: 0= CALL ;
: 0< CALL ;
: 0> CALL ;
: 0<> CALL ;

: C! CALL ;
: C@ CALL ;
: +! CALL ;
: CELLS 8 * ;
: CHARS ;
: HERE CALL ;
: ALLOT CALL ;
: , CALL ;

: TYPE CALL ;
: COUNT DUP 1+ SWAP C@ ;
: -TRAILING BEGIN DUP 0> WHILE 2DUP + 1- C@ 32 = WHILE 1- REPEAT THEN ;
: ." CALL ;
: S" CALL ;

: STATE CALL ;
: LATEST CALL ;
: HEADER CALL ;
: FIND CALL ;
: ' WORD FIND 0= IF ABORT THEN ;
: IMMEDIATE CALL ;
: HIDDEN CALL ;
: CREATE CALL ;
: DOES> CALL ;
: VARIABLE CREATE 0 , ;
: CONSTANT CREATE , DOES> @ ;
: : CALL ;
: ; EXIT ; IMMEDIATE

: IF CALL ; IMMEDIATE
: ELSE CALL ; IMMEDIATE
: THEN CALL ; IMMEDIATE
: BEGIN CALL ; IMMEDIATE
: UNTIL CALL ; IMMEDIATE
: WHILE CALL ; IMMEDIATE
: REPEAT CALL ; IMMEDIATE
: DO CALL ; IMMEDIATE
: LOOP CALL ; IMMEDIATE
: RECURSE CALL ; IMMEDIATE

: WORD CALL ;
: NUMBER? CALL ;
: >NUMBER CALL ;
: INTERPRET CALL ;
: ABORT CALL ;
: QUIT CALL ;

: EMIT CALL ;
: KEY CALL ;
: . CALL ;
: CR 10 EMIT ;
: SPACE 32 EMIT ;
: SPACES 0 DO SPACE LOOP ;
: DUMP CALL ;
: WORDS CALL ;
: .S CALL ;
: BYE CALL ;

: ASSERT= CALL ;
: SUMMARY CALL ;
